[en]
    title = "CodeBoy.dev"
    languageCode = "en"
    weight = 1
    [en.params]
        cbd = "CodeBoy.dev"

[fr]
    title = "CodeBoy.dev"
    languageCode = "fr"
#    contentDir = "content"
    weight = 2
    [fr.params]
        cbd = "CodeBoy.dev"
